### ISSUE TITLE
Average waiting time

### ISSUE THREAD

**Issue by chintanpokhrel** [Aronswar/rainowproject#3]
I think the problem is asking you to calculate the mean waiting time / id. You will perhaps not get any input to this API. The simple way to do it would be to sum up (now - start_time) for all values in the dictionary divided by the length of the dictionary. However, you would also like to delete the item from the dict while popping from the queue

**Comment by Aronswar** [comment]
i saw that also....I just re implemented by summing up the times and dividing it by the length
